default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: meal_kit_subscription_development

test:
  <<: *default
  database: meal_kit_subscription_test
